import { Inter } from 'next/font/google'
import './globals.css'
import Typingtext from './comp/Typingtext'
const inter = Inter({ subsets: ['latin'] })
import Header from './pages/header/page'
import Scroll from './pages/scroll/page'
import Footer from './pages/footer/page'
import About from './pages/about/page'
import Skill from './pages/skill/page'
import Work from './pages/work/page'
import Contact from './pages/contact/page'
import RandomBalls from './pages/mouse/page';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Header/>
          <Scroll/>
        </header>
        <main>
          <div id='wrap'></div>
          <RandomBalls/>
          
        </main>
      </body>
    </html>
  )
}

