import RandomBalls from './pages/mouse/page';
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
import Header from './pages/header/page'
import Scroll from './pages/scroll/page'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <div id='wrap'></div>
          <RandomBalls/>
        <header>
          <Header/>
          <Scroll/>
        </header>
        <main>
        </main>
      </body>
    </html>
  )
}

